services:

    sg_calendar.event_manager:
        class: Sg\CalendarBundle\Manager\EventManager
        arguments: [@doctrine.orm.entity_manager, %sg_calendar.event_class%]

    sg_calendar.form_factory:
        class: Sg\CalendarBundle\Form\Factory\EventFormFactory
        arguments: [@form.factory, 'Testname', %sg_calendar.event_form_type%]

    sg_calendar.event_form_type:
        class: Sg\CalendarBundle\Form\Type\EventType
        arguments: [%sg_calendar.event_class%]
        tags:
            - { name: form.type, alias: sg_calendar_eventtype }