services:

    sg_calendar.twig_extension:
        class: Sg\CalendarBundle\Twig\CalendarExtension
        arguments: [@twig, %sg_calendar.first_day%, %sg_calendar.time_format%]
        tags:
            - { name: twig.extension }

    sg_calendar.event_manager:
        class: Sg\CalendarBundle\Manager\EventManager
        arguments: [@doctrine.orm.entity_manager, %sg_calendar.event.class%]

    sg_calendar.form_type.event.default:
        class: Sg\CalendarBundle\Form\Type\EventType
        arguments: [%sg_calendar.event.class%]
        tags:
            - { name: form.type, alias: sg_calendar_eventtype }

    sg_calendar.form_factory.event:
        class: Sg\CalendarBundle\Form\Factory\EventFormFactory
        arguments: [@form.factory, %sg_calendar.form.event.name%, %sg_calendar.form.event.type%]

    sg_calendar.subscriber.calendar:
        class: Sg\CalendarBundle\Subscriber\CalendarSubscriber
        arguments: [@session, @router, @translator]
        tags:
            - { name: kernel.event_subscriber }

    sg_calendar.subscriber.orm:
        class: Sg\CalendarBundle\Subscriber\OrmSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }

    sg_calendar.array_generator:
        class: Sg\CalendarBundle\Generator\EventsToArray
        arguments: [@router]

    sg_calendar.voter.access.owner:
        class: Sg\CalendarBundle\Voter\OwnerVoter
        tags:
            - { name: security.voter }