services:

    sg_calendar.twig_extension:
        class: Sg\CalendarBundle\Twig\CalendarExtension
        arguments: [@twig, %sg_calendar.twig.fullcalendar_id%, %sg_calendar.twig.datepicker_id%, %sg_calendar.twig.first_day%, %sg_calendar.twig.time_format%]
        tags:
            - { name: twig.extension }

    sg_calendar.event_manager:
        class: Sg\CalendarBundle\Doctrine\EventManager
        arguments: [@doctrine.orm.entity_manager, %sg_calendar.doctrine.event.class%]

    sg_calendar.calendar_manager:
        class: Sg\CalendarBundle\Doctrine\CalendarManager
        arguments: [@doctrine.orm.entity_manager, %sg_calendar.doctrine.calendar.class%]

    sg_calendar.form_type.event.default:
        class: Sg\CalendarBundle\Form\Type\EventType
        arguments: [%sg_calendar.doctrine.event.class%]
        tags:
            - { name: form.type, alias: sg_calendar_eventtype }

    sg_calendar.form_type.calendar.default:
        class: Sg\CalendarBundle\Form\Type\CalendarType
        arguments: [%sg_calendar.doctrine.calendar.class%]
        tags:
            - { name: form.type, alias: sg_calendar_calendartype }

    sg_calendar.form_factory.event:
        class: Sg\CalendarBundle\Form\Factory\EventFormFactory
        arguments: [@form.factory, %sg_calendar.form.event.name%, %sg_calendar.form.event.type%]

    sg_calendar.form_factory.calendar:
        class: Sg\CalendarBundle\Form\Factory\CalendarFormFactory
        arguments: [@form.factory, %sg_calendar.form.calendar.name%, %sg_calendar.form.calendar.type%]

    sg_calendar.subscriber.calendar:
        class: Sg\CalendarBundle\Subscriber\CalendarSubscriber
        arguments: [@session, @router, @translator]
        tags:
            - { name: kernel.event_subscriber }

    sg_calendar.subscriber.orm:
        class: Sg\CalendarBundle\Doctrine\Orm\OrmSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }

    sg_calendar.array_generator:
        class: Sg\CalendarBundle\Generator\EventsToArray
        arguments: [@router]

    sg_calendar.voter.access.owner:
        class: Sg\CalendarBundle\Security\Authorization\Voter\EventVoter
        tags:
            - { name: security.voter }